name: erisk_mock_server
channels:
  - conda-forge
dependencies:
  - matplotlib>=3.5.1,<3.6.0
  - scikit-learn>=1.0.0,<1.1.0
  - numpy>=1.19.0,<2.0.0
  - python=3.7
  - flake8
  - pytest
  - pre-commit
  - pip
  - pip:
    - black
    - arviz>=0.11.4,<0.12.0
    - uvicorn[standard]
    - fastapi>=0.70.1,<0.71.0
    - databases[sqlite]
    - httpx
    - gunicorn
